name: ptliangyuetian
description: 一个自己玩的app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.13
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  quiver: ^2.0.5
  #  connectivity: ^0.4.3+6
  # 网络请求
  dio: 3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  # 本地存储
  shared_preferences: ^0.5.2
  # 本地json对象存储
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.10.4

  # 状态管理
  provider: ^3.0.0+1
  # 加密
  encrypt: ^3.2.0
  # 打开文件，android更新下载安装包用
  open_file: ^2.0.3
  # flare动画
  flare_flutter: ^1.5.5
  # 打开web页面
  flutter_webview_plugin: ^0.3.8
  # 事件模拟，订阅发布
  event_bus: ^1.1.0
  # 路由
  fluro: ^1.5.1
  flutter_plugin_pdf_viewer: ^1.0.7
  path_provider: ^1.3.0

  # UI
  oktoast: ^2.2.0
  pull_to_refresh: ^1.5.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bAvqIeblkajqaqA.jpg
    - assets/images/0069lnCQly1fi6knj5e8xj30xc0ma75u.jpg
    - assets/images/006i7H6Hgy1fjyd32bpqhj319c1w0kjm.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
